version: "3.8"

services:
  app:
    ## o ("."), indica que a imagem do Docker sera construida no Directorio atual
    build: . 
    command: /bin/sh -c "npm install && npm start"
    ## Mapeia a porta 5000 do containerpara porta 5000 da maquina
    ports:
      - "5000:5000"
    ## Monta o diretório atual da maquina host no diretorio usr/app dentro do container
    volumes:
      - .:/usr/app
    ## Indica que o serviço app depende do serviço db
    depends_on:
      - db

  db:
    image: mysql:8.0
    ## Configura para reiniciar automaticamente caso ele pare
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senai@604
      MYSQL_DATABASE: vio_pedro
    ## Mapeia a porta 3306 do container para porta 3306 da maquina
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
